### ISSUE TITLE
Create a footer?

### ISSUE THREAD

**Issue by brunobraga95** [brunobraga95/FIFA-manager#17]
The bottom of the page looks to empty, it does not need to be a footer itself, but something to make the page look less empty.

**Comment by tiagoalvesdulce** [comment]
I don't think a footer will fit well in this kind of application. As soon as the user has some info logged in the app, it will not look that empty. But I can make the page 'thinner' tho, it will give the idea that it's larger vertically but might look empty on the sides.

**Comment by brunobraga95** [comment]
sounds good!
