### ISSUE TITLE
Get Teams list from files folder and use it on FrontEnd

### ISSUE THREAD

**Issue by brunobraga95** [brunobraga95/FIFA-manager#18]
In the root folder there is another folder called files, there you can find a file called teamList, this file is in the format of an array of arrays, use it on frontEnd so that users cannot enter team name anymore, but choose it from a pre defined list.

**Comment by brunobraga95** [comment]
Tiago use adapt-teamsList-FrontEnd branch
 to added the teams list on frontEnd, I already started doing it, add some style to it.

**Comment by brunobraga95** [comment]
UP

**Comment by brunobraga95** [comment]
UP, the FrontEnd still needs to solve this issue.

**Comment by tiagoalvesdulce** [comment]
Solved
