### ISSUE TITLE
Create an API?

### ISSUE THREAD

**Issue by tiagoalvesdulce** [brunobraga95/FIFA-manager#22]
I've been thinking about making our app able to different platforms (Android, iOS, Web, etc) and I think that the best way is to create a RESTFUL API, this way we would be able to retrieve important information from firebase (or another database) through some endpoints (like we did with the Oak dashboard). I don't know the best way to do this tho.

It would work like this:

Firebase (or another database) -----> API -----> APP.

This way our production would be more robust and if we want to change our app from hybrid to native one day, it would be easier.

This way, I suggest taking a look at this after the initial prototype is done, what do you think?

**Comment by brunobraga95** [comment]
This is a good idea, we should start working on  that. 
https://firebase.google.com/docs/database/rest/start

**Comment by fernandoabolafio** [comment]
I've reading about it Im not sure having an API fits the App priorities right now unless we will need some data processing our consume another API which is not available trought Firebase. 

Take a look on it: https://firebase.googleblog.com/2013/03/where-does-firebase-fit-in-your-app.html

**Comment by brunobraga95** [comment]
We decided that the API call is not the best idea, firebase documentation is very simple and straight forward, we can use it in different languages without a problem.
