### ISSUE TITLE
lines 545 and 546 crashing WebApp

### ISSUE THREAD

**Issue by brunobraga95** [brunobraga95/FIFA-manager#26]
545: graficoResumo.data.datasets[0].data = [userInfo.venceu, userInfo.empatou, userInfo.perdeu];
546: graficoResumo.update();

These two lines do not work for some reason, they crash the code saying that data is not defined

**Comment by tiagoalvesdulce** [comment]
Let's just forget about them for now. They are related to the chart and we can fix it as soon as we finish more important parts.

**Comment by tiagoalvesdulce** [comment]
Solved
