### ISSUE TITLE
Use a specific object for each friend/group

### ISSUE THREAD

**Issue by tiagoalvesdulce** [brunobraga95/FIFA-manager#28]
I think we should have an object to control what we will display on the screen. Right now we have just the userInfo object. It would be something like 1 "general" object (like userInfo), 1 per group and 1 per friend.

**Comment by brunobraga95** [comment]
I believe the most important step right now is to keep coding the FrontEnd so that the project will not stall. But we can think more about it later.

**Comment by tiagoalvesdulce** [comment]
The problem is that affects some parts of the frontend like the charts for example. Now, we do have to change the userInfo object and then call the Partial and then change it again if the user decides to live the page. I'm thinking about creating independent objects in the beginning and add them as soon as we create groups or add friends. It is a little confusing now. You can go ahead and do that and I'll focus on the design aspects a little bit

**Comment by brunobraga95** [comment]
I did not really understand what you mean, if you could please create a sample Json object with fake data to represent the type of objects you need, would be good.

**Comment by tiagoalvesdulce** [comment]
It would be mostly a frontend thing. Imagine when we are retrieving information from firebase after the user logs in, we put "everything" we need into userInfo, right? But I think that a most organized and maintainable way would be creating different objects for each group and friend. Imagine if a friend has its own object, for example, this way we wouldn't need to change userInfo every single time when the user clicks in "Geral" and go back to a friend. It would be especially useful with the Charts because each object will store the data to populate it properly.

**Comment by tiagoalvesdulce** [comment]
Solved
